;;; zk-agenda-view-tests.el --- Inline day/week and standalone year -*- lexical-binding: t; -*-
(require 'zk-test-helper)

(defun zk-test-view-date (day &optional clock)
  (let ((date (calendar-gregorian-from-absolute day)))
    (format "<%04d-%02d-%02d%s>" (nth 2 date) (car date) (nth 1 date)
            (if clock (concat " " clock) ""))))

(defun zk-test-view-fixture ()
  (let* ((range (zk-agenda-range 'week)) (monday (car range)) (today (org-today)))
    (zk-test-write
     (zk-agenda-path)
     (concat "* Calendar\n** Current day\n" (zk-test-view-date today "14:00") "\n"
             "** Monday\n" (zk-test-view-date monday "09:00") "\n"
             "** Sunday event\n" (zk-test-view-date (+ monday 6) "16:00") "\n"
             "** Outside week\n" (zk-test-view-date (+ monday 7) "12:00") "\n"))))

(ert-deftest zk-agenda-view-ranges-handle-week-and-year-boundaries ()
  (let* ((sunday (calendar-absolute-from-gregorian '(1 3 2027)))
         (monday (calendar-absolute-from-gregorian '(12 28 2026))))
    (should (equal (cons monday 7) (zk-agenda-range 'week sunday)))
    (should (equal (cons sunday 1) (zk-agenda-range 'day sunday)))
    (should (equal (cons (calendar-absolute-from-gregorian '(1 1 2024)) 366)
                   (zk-agenda-range 'year (calendar-absolute-from-gregorian '(2 29 2024))))))
  (should (= 365 (cdr (zk-agenda-range 'year (calendar-absolute-from-gregorian '(12 31 2026)))))))

(ert-deftest zk-agenda-view-switches-in-home-and-keeps-other-sections ()
  (zk-test-library
   (zk-test-view-fixture) (zk-capture "Inbox stays") (zk-note-create "Note stays.org")
   (zk-home)
   (let ((home (current-buffer)) (window (selected-window))
         (inbox (plist-get zk-home--data :inbox)) (notes (plist-get zk-home--data :notes)))
     (cl-letf (((symbol-function 'zk-inbox-entries) (lambda () (error "Do not rescan Inbox")))
               ((symbol-function 'zk-notes) (lambda () (error "Do not rescan notes"))))
       (call-interactively (key-binding "w"))
       (should (eq home (current-buffer))) (should (eq window (selected-window)))
       (should (eq zk-home--agenda-view 'week))
       (should (= 7 (seq-count (lambda (row) (eq (plist-get row :kind) 'date))
                               (plist-get zk-home--data :agenda))))
       (should (string-match-p "Sunday event" (buffer-string)))
       (should (string-match-p "Monday" (buffer-string)))
       (should-not (string-match-p "Outside week" (buffer-string)))
       (call-interactively (key-binding "d"))
       (should (eq zk-home--agenda-view 'day))
       (should (= 1 (seq-count (lambda (row) (eq (plist-get row :kind) 'date))
                               (plist-get zk-home--data :agenda))))
       (should (eq inbox (plist-get zk-home--data :inbox)))
       (should (eq notes (plist-get zk-home--data :notes))))
     (should-not (get-buffer "*Org Agenda*")))))

(ert-deftest zk-agenda-view-week-survives-refresh-native-edit-and-clock ()
  (zk-test-library
   (let ((org-todo-keywords (list zk-org-todo-keywords))
         (org-use-fast-todo-selection t) (org-agenda-skip-scheduled-if-done nil))
     (zk-test-view-fixture) (zk-home) (zk-home-agenda-week)
     (goto-char (point-min)) (search-forward "Sunday event") (backward-char 2)
     (cl-letf (((symbol-function 'org-fast-todo-selection) (lambda (&rest _) "DONE")))
       (call-interactively (key-binding "t")))
     (should (eq zk-home--agenda-view 'week))
     (should (equal "*ZK*" (buffer-name)))
     (should (equal "Sunday event" (plist-get (get-text-property (point) 'zk-entry) :title)))
     (should (equal "DONE" (plist-get (get-text-property (point) 'zk-entry) :state)))
     (zk-home--update '(agenda))
     (zk-home-refresh)
     (should (eq zk-home--agenda-view 'week))
     (should (= 7 (seq-count (lambda (row) (eq (plist-get row :kind) 'date))
                             (plist-get zk-home--data :agenda))))
     (should (equal "Sunday event" (plist-get (get-text-property (point) 'zk-entry) :title))))))

(ert-deftest zk-agenda-view-per-view-cache-and-daily-api-remain-independent ()
  (zk-test-library
   (zk-test-view-fixture)
   (let ((builder (symbol-function 'zk-agenda--build-rows))
         (formatter (symbol-function 'format-time-string)) (builds 0))
     (cl-letf (((symbol-function 'zk-agenda--build-rows)
                (lambda (&rest args) (cl-incf builds) (apply builder args)))
               ((symbol-function 'format-time-string)
                (lambda (format &rest args)
                  (if (equal format "%Y-%m-%d %H:%M") "fixed-minute"
                    (apply formatter format args)))))
       (zk-agenda-rows 'day 100) (zk-agenda-rows 'week 100)
       (zk-agenda-rows 'day 100) (zk-agenda-rows 'week 100)
       (should (= builds 2))
       (with-current-buffer (get-file-buffer (zk-agenda-path)) (goto-char (point-max)) (insert "\n"))
       (zk-agenda-rows 'week 100)
       (should (= builds 3))))
   (zk-home) (zk-home-agenda-week)
   (let ((rows (plist-get zk-home--data :agenda)) (items (zk-today-items)))
     (should (seq-some (lambda (item) (equal (plist-get item :title) "Current day")) items))
     (should-not (seq-some (lambda (item) (equal (plist-get item :title) "Outside week")) items))
     (should (eq rows (plist-get zk-home--data :agenda)))
     (should (eq zk-home--agenda-view 'week)))))

(ert-deftest zk-agenda-view-year-opens-native-buffer-for-the-calendar-year ()
  (zk-test-library
   (let* ((range (zk-agenda-range 'year)) (start (car range)) (end (+ start (1- (cdr range)))))
     (zk-test-write (zk-agenda-path)
                    (concat "* Calendar\n** First day\n" (zk-test-view-date start) "\n"
                            "** Last day\n" (zk-test-view-date end) "\n"
                            "** Outside year\n" (zk-test-view-date (1+ end)) "\n"))
     (zk-home) (zk-home-agenda-week)
     (call-interactively (key-binding "y"))
     (should (eq major-mode 'org-agenda-mode))
     (should (= start org-starting-day))
     (should (string-match-p "First day" (buffer-string)))
     (should (string-match-p "Last day" (buffer-string)))
     (should-not (string-match-p "Outside year" (buffer-string)))
     (should-not org-agenda-show-all-dates)
     (should-not org-agenda-use-time-grid)
     (org-agenda-redo)
     (should (string-match-p "Last day" (buffer-string)))
     (should-not org-agenda-show-all-dates)
     (should-not org-agenda-use-time-grid)
     (with-current-buffer "*ZK*" (should (eq zk-home--agenda-view 'week))))))

(ert-deftest zk-agenda-view-empty-and-menu-entrypoints ()
  (zk-test-library
   (zk-week)
   (should (equal "*ZK*" (buffer-name)))
   (should (eq zk-home--agenda-view 'week))
   (should (= 7 (seq-count (lambda (row) (eq (plist-get row :kind) 'date))
                           (plist-get zk-home--data :agenda))))
   (zk-today)
   (should (eq zk-home--agenda-view 'day))
   (should-not (string-match-p (regexp-opt '("Day [d]" "Week [w]" "Year [y]")) (buffer-string)))
   (call-interactively (key-binding "w"))
   (should (eq zk-home--agenda-view 'week))
   (should (string-prefix-p "Agenda" (thing-at-point 'line t)))
   (should-error (zk-home-toggle-section) :type 'user-error)))

(ert-deftest zk-agenda-view-failed-generation-retains-current-view-and-content ()
  (zk-test-library
   (zk-home)
   (let ((before (buffer-string)) (position (point)))
     (cl-letf (((symbol-function 'zk-agenda-rows) (lambda (&rest _) (error "Failed"))))
       (should-error (zk-home-agenda-week)))
     (should (eq zk-home--agenda-view 'day))
     (should (equal before (buffer-string))) (should (= position (point))))))
