;;; zk-home-tests.el --- Home checks -*- lexical-binding: t; -*-
(require 'zk-test-helper)

(ert-deftest zk-home-shows-next-inbox-and-notes ()
  (zk-test-library
   (zk-test-task "NEXT" "Ready action")
   (zk-capture "Unprocessed idea") (zk-note-create "Knowledge.org")
   (should (buffer-live-p (zk-home)))
   (should (equal "*ZK*" (buffer-name)))
   (should-not header-line-format)
   (should (= 0 left-fringe-width))
   (should (string-match-p "Ready action" (buffer-string)))
   (should (string-match-p "Unprocessed idea" (buffer-string)))
   (should (string-match-p "Knowledge" (buffer-string)))
   (should-not (eq (key-binding "N") 'zk-choose-next))))

(ert-deftest zk-home-table-adapts-without-breaking-entry-actions ()
  (let ((entry '(:title "一个较长的标题 with additional English words for testing"
                        :file "example.org" :path ("Work" "Project" "Task")
                        :tags ("knowledge" "emacs") :created "[2026-09-30 Wed]"
                        :origin "Inbox capture")))
    (dolist (width '(30 61 80 104 105 160))
      (dolist (kind '(task inbox note))
        (with-temp-buffer
          (let ((columns (zk-home--table-columns kind width)))
            (zk-home--table-row entry kind columns)
            (goto-char (point-min))
            (should
             (<= (string-width (buffer-substring-no-properties (point) (line-end-position))) width))
            (should (button-at (+ (point-min) (if (eq kind 'task) 5 0))))
            (should (equal entry (get-text-property (point-min) 'zk-entry)))
            (should (= (length columns) (cond ((< width 62) 1) ((< width 105) 2) (t 3))))))))))

(ert-deftest zk-tab-toggles-current-section-from-any-row ()
  (zk-test-library
   (let ((zk-home-item-limit 2))
     (dotimes (i 7) (zk-capture (format "Inbox item %d" i)))
     (zk-home)
     (goto-char (zk-home--section-start "Inbox"))
     (should (eq (key-binding (kbd "TAB")) 'zk-home-toggle-section))
     (zk-home-toggle-section)
     (should (member "Inbox" zk-home--expanded))
     (search-forward "Inbox item 0")
     (zk-home-toggle-section)
     (should-not (member "Inbox" zk-home--expanded))
     (should (= (point) (zk-home--section-start "Inbox")))
     (should-not (string-match-p "Inbox item 0" (buffer-string)))
     (zk-home-toggle-section)
     (should (string-match-p "Inbox item 0" (buffer-string))))))

(ert-deftest zk-tab-keeps-a-preview-entry-selected ()
  (zk-test-library
   (let ((zk-home-item-limit 2))
     (dotimes (i 4) (zk-capture (format "Entry %d" i)))
     (zk-home)
     (goto-char (point-min)) (search-forward "Entry 3")
     (let ((entry (get-text-property (1- (point)) 'zk-entry)))
       (backward-char)
       (zk-home-toggle-section)
       (should (eq entry (get-text-property (point) 'zk-entry)))
       (zk-home-toggle-section)
       (should (eq entry (get-text-property (point) 'zk-entry)))))))

(ert-deftest zk-tab-sections-remain-independent-without-visible-toggle-controls ()
  (zk-test-library
   (let ((zk-home-item-limit 1))
     (dotimes (i 3) (zk-capture (format "Pending %d" i)) (zk-note-create (format "Note %d.org" i)))
     (zk-home)
     (zk-home-toggle-section "Inbox")
     (should (member "Inbox" zk-home--expanded))
     (should-not (member "Notes" zk-home--expanded))
     (goto-char (zk-home--section-start "Notes"))
     (should-not (string-match-p (regexp-opt '("Show all" "Show less" "[TAB]")) (buffer-string)))
     (should-not (string-match-p (regexp-opt '("TAB" "all/less")) (format "%s" mode-line-format)))
     (zk-home-toggle-section)
     (should (member "Notes" zk-home--expanded))
     (should-not (string-match-p (regexp-opt '("Show all" "Show less" "[TAB]")) (buffer-string)))
     (goto-char (point-max))
     (zk-home-toggle-section)
     (should-not (member "Notes" zk-home--expanded))
     (should (member "Inbox" zk-home--expanded))
     (should (= (point) (zk-home--section-start "Notes"))))))

(ert-deftest zk-tab-leaves-today-and-small-sections-alone ()
  (zk-test-library
   (zk-capture "Single")
   (zk-home)
   (goto-char (zk-home--section-start "Inbox"))
   (zk-home-toggle-section)
   (should-not zk-home--expanded)
   (goto-char (point-min)) (search-forward "Agenda")
   (should-error (zk-home-toggle-section) :type 'user-error)
   (should-not zk-home--expanded)))
