;;; zk-home-agenda-tests.el --- Native Agenda commands from Home -*- lexical-binding: t; -*-
(require 'zk-test-helper)

(defmacro zk-test-home-agenda (&rest body)
  (declare (indent 0))
  (list 'zk-test-library
        (append '(let ((org-todo-keywords (list zk-org-todo-keywords))
                       (org-use-fast-todo-selection nil)
                       (org-agenda-skip-scheduled-if-done nil))) body)))

(defun zk-test-home-today-task (&optional state)
  (let* ((task (zk-test-task (or state "TODO") "Agenda action"))
         (dated (zk-task-update task :scheduled (format-time-string "%Y-%m-%d 16:00"))))
    (zk-home)
    (goto-char (point-min)) (search-forward "Agenda action")
    dated))

(ert-deftest zk-home-agenda-t-calls-native-command-and-stays-in-home ()
  (zk-test-home-agenda
    (let* ((task (zk-test-home-today-task)) (native (symbol-function 'org-agenda-todo))
           (home (current-buffer)) (window (selected-window)) called)
      (cl-letf (((symbol-function 'org-agenda-todo)
                 (lambda (&optional arg) (interactive "P")
                   (setq called (derived-mode-p 'org-agenda-mode))
                   (should-not (get-buffer-window (current-buffer) t))
                   (funcall native arg)))
                ((symbol-function 'zk-next) (lambda () (error "Do not use ZK state wrappers")))
                ((symbol-function 'zk-task-update) (lambda (&rest _) (error "Use native Agenda"))))
        (call-interactively (key-binding (kbd "t"))))
      (should called)
      (should (eq home (current-buffer)))
      (should (eq window (selected-window)))
      (should (eq home (window-buffer window)))
      (should (equal "NEXT" (plist-get (zk-entry-read (plist-get task :id)) :state)))
      (should (equal (plist-get task :id) (plist-get (get-text-property (point) 'zk-entry) :id))))))

(ert-deftest zk-home-agenda-fast-selection-completes-and-refreshes-next ()
  (zk-test-home-agenda
    (let* ((task (zk-test-home-today-task "NEXT")) (org-use-fast-todo-selection t)
           (org-log-done 'time))
      (cl-letf (((symbol-function 'org-fast-todo-selection) (lambda (&rest _) "DONE")))
        (call-interactively (key-binding "t")))
      (should (equal "*ZK*" (buffer-name)))
      (should-not (seq-some (lambda (e) (equal (zk-task-display-state e) "NEXT")) (plist-get (plist-get zk-home--data :todos) :daily)))
      (should (seq-some (lambda (row) (equal "DONE" (plist-get (plist-get row :entry) :state)))
                        (plist-get zk-home--data :agenda)))
      (with-current-buffer (get-file-buffer (zk-agenda-path))
        (goto-char (zk-org-locate (plist-get task :id)))
        (should (org-entry-get nil "CLOSED"))
        (should-not (buffer-modified-p))))))

(ert-deftest zk-home-agenda-native-repeater-rolls-forward ()
  (zk-test-home-agenda
    (let* ((task (zk-test-task "NEXT" "Repeating action"))
           (dated (zk-task-update task :scheduled (concat (format-time-string "%Y-%m-%d 10:00") " +1w")))
           (org-use-fast-todo-selection t))
      (zk-home) (goto-char (point-min)) (search-forward "Repeating action")
      (cl-letf (((symbol-function 'org-fast-todo-selection) (lambda (&rest _) "DONE")))
        (zk-home-agenda-todo))
      (let ((updated (zk-entry-read (plist-get dated :id))))
        (should (equal "TODO" (plist-get updated :state)))
        (should (> (org-time-string-to-absolute (plist-get updated :scheduled)) (org-today))))
      (should (equal "*ZK*" (buffer-name))))))

(ert-deftest zk-home-agenda-keeps-earlier-unsaved-source-edits ()
  (zk-test-home-agenda
    (zk-test-home-today-task)
    (with-current-buffer (get-file-buffer (zk-agenda-path))
      (goto-char (point-min)) (insert "#+title: Unsaved draft\n"))
    (zk-home-agenda-todo)
    (with-current-buffer (get-file-buffer (zk-agenda-path))
      (should (buffer-modified-p))
      (should (string-prefix-p "#+title: Unsaved draft" (buffer-string))))
    (with-temp-buffer
      (insert-file-contents (zk-agenda-path))
      (should-not (string-match-p "Unsaved draft" (buffer-string)))
      (should (string-match-p "TODO Agenda action" (buffer-string))))))

(ert-deftest zk-home-agenda-stale-selection-does-not-update-wrong-content ()
  (zk-test-home-agenda
    (let ((task (zk-test-home-today-task)))
      (with-current-buffer (get-file-buffer (zk-agenda-path))
        (goto-char (zk-org-locate task)) (org-edit-headline "Changed elsewhere"))
      (should-error (zk-home-agenda-todo) :type 'user-error)
      (should (equal "TODO" (plist-get (zk-entry-read (plist-get task :id)) :state)))
      (should (equal "*ZK*" (buffer-name))))))

(ert-deftest zk-home-agenda-structural-and-other-sections-dont-open-agenda ()
  (zk-test-home-agenda
    (zk-test-home-today-task)
    (dolist (label '("Agenda" "Todos" "Notes"))
      (goto-char (point-min)) (search-forward label)
      (should-error (zk-home-agenda-todo) :type 'user-error)
      (should (equal "*ZK*" (buffer-name))))))

(ert-deftest zk-home-agenda-native-schedule-and-deadline ()
  (zk-test-home-agenda
    (let* ((task (zk-test-home-today-task)) (schedule (symbol-function 'org-agenda-schedule))
           (deadline (symbol-function 'org-agenda-deadline))
           (day (format-time-string "%Y-%m-%d")))
      (cl-letf (((symbol-function 'org-agenda-schedule)
                 (lambda (arg) (interactive "P") (funcall schedule arg (concat day " 17:00")))))
        (call-interactively (key-binding (kbd "C-c C-s"))))
      (should (equal "*ZK*" (buffer-name)))
      (should (string-match-p "17:00" (plist-get (zk-entry-read (plist-get task :id)) :scheduled)))
      (cl-letf (((symbol-function 'org-agenda-deadline)
                 (lambda (arg) (interactive "P") (funcall deadline arg day))))
        (call-interactively (key-binding (kbd "C-c C-d"))))
      (should (equal "*ZK*" (buffer-name)))
      (should (plist-get (zk-entry-read (plist-get task :id)) :deadline))
      (let ((current-prefix-arg '(4)))
        (call-interactively (key-binding (kbd "C-c C-d"))))
      (should-not (plist-get (zk-entry-read (plist-get task :id)) :deadline)))))

(ert-deftest zk-home-agenda-aborted-selection-leaves-source-and-screen-intact ()
  (zk-test-home-agenda
    (let* ((task (zk-test-home-today-task)) (before (plist-get (zk-entry-read task) :body))
           (org-use-fast-todo-selection t))
      (cl-letf (((symbol-function 'org-fast-todo-selection) (lambda (&rest _) (signal 'quit nil))))
        (should (eq 'quit (condition-case nil (zk-home-agenda-todo) (quit 'quit)))))
      (should (equal before (plist-get (zk-entry-read task) :body)))
      (should (equal "*ZK*" (buffer-name))))))

(ert-deftest zk-home-agenda-idless-event-can-become-a-todo-in-place ()
  (zk-test-home-agenda
    (zk-test-write (zk-agenda-path)
                   (format "* Life\n** Event\nSCHEDULED: <%s 16:00>\n"
                           (format-time-string "%Y-%m-%d %a")))
    (zk-home) (goto-char (point-min)) (search-forward "Event")
    (let ((result (zk-home-agenda-todo)))
      (should (equal "TODO" (plist-get result :state)))
      (should-not (plist-get result :id))
      (should (get-text-property (point) 'zk-agenda-row))
      (should (equal "*ZK*" (buffer-name))))))

(ert-deftest zk-home-agenda-native-blocker-prevents-completion ()
  (zk-test-home-agenda
    (let* ((task (zk-test-home-today-task "NEXT")) (org-use-fast-todo-selection t)
           (org-blocker-hook (list (lambda (_change) nil))))
      (cl-letf (((symbol-function 'org-fast-todo-selection) (lambda (&rest _) "DONE")))
        (zk-home-agenda-todo))
      (should (equal "NEXT" (plist-get (zk-entry-read (plist-get task :id)) :state)))
      (should (equal "*ZK*" (buffer-name))))))
