;;; zk-home-cursor-tests.el --- Selection survives redraws -*- lexical-binding: t; -*-
(require 'zk-test-helper)

(defun zk-test-cursor-fixture ()
  (zk-test-write (zk-agenda-path)
                 (format "* Life\n** NEXT Earlier\nSCHEDULED: <%s 09:00>\n** NEXT Selected\nSCHEDULED: <%s 16:00>\n"
                         (format-time-string "%Y-%m-%d %a") (format-time-string "%Y-%m-%d %a")))
  (zk-home)
  (goto-char (point-min)) (search-forward "Selected") (backward-char 3))

(ert-deftest zk-home-cursor-idless-task-stays-selected-through-queued-refresh ()
  (zk-test-library
   (let ((org-todo-keywords (list zk-org-todo-keywords))
         (org-use-fast-todo-selection t)
         (org-agenda-skip-scheduled-if-done nil)
         (zk-change-hook '(zk-home-request-refresh)))
     (zk-test-cursor-fixture)
     (let* ((column (current-column))
            (source (plist-get (get-text-property (point) 'zk-entry) :position)))
       (cl-letf (((symbol-function 'org-fast-todo-selection) (lambda (&rest _) "DONE")))
         (zk-home-agenda-todo))
       (should (= source (plist-get (get-text-property (point) 'zk-entry) :position)))
       (should (= column (current-column)))
       ;; Exercise the actual deferred callback that previously selected Earlier.
       (let ((timer zk-home--timer))
         (should (timerp timer))
         (cancel-timer timer)
         (funcall (timer--function timer)))
       (should (= source (plist-get (get-text-property (point) 'zk-entry) :position)))
       (should (string-match-p "DONE Selected" (thing-at-point 'line t)))
       (should (= column (current-column)))
       (should (equal "Agenda" (get-text-property (point) 'zk-section)))))))

(ert-deftest zk-home-cursor-same-task-in-next-and-today-keeps-section-and-column ()
  (zk-test-library
   (let ((org-todo-keywords (list zk-org-todo-keywords)))
     (zk-test-cursor-fixture)
     (goto-char (zk-home--section-start "Todos"))
     (search-forward "Selected")
     (let ((column (current-column)))
       (zk-home-refresh)
       (should (equal "Todos" (get-text-property (point) 'zk-section)))
       (should (= column (current-column)))
       (should (string-match-p "Selected" (thing-at-point 'line t)))))))

(ert-deftest zk-home-cursor-idless-entry-follows-live-marker-after-earlier-edits ()
  (zk-test-library
   (zk-test-cursor-fixture)
   (with-current-buffer (get-file-buffer (zk-agenda-path))
     (goto-char (point-min)) (insert "#+title: Added before the task\n"))
   (zk-home-refresh)
   (should (equal "Selected" (plist-get (get-text-property (point) 'zk-entry) :title)))))

(ert-deftest zk-home-cursor-scheduled-and-deadline-occurrences-stay-distinct ()
  (zk-test-library
   (let* ((day (format-time-string "%Y-%m-%d %a"))
          (org-agenda-skip-deadline-prewarning-if-scheduled nil))
     (zk-test-write (zk-agenda-path)
                    (format "* Life\n** TODO Twice\nDEADLINE: <%s> SCHEDULED: <%s 14:00>\n" day day))
     (zk-home)
     (let (positions)
       (goto-char (point-min))
       (while (search-forward "Twice" nil t)
         (when (get-text-property (line-beginning-position) 'zk-agenda-row)
           (push (line-beginning-position) positions)))
       (should (= 2 (length positions)))
       (goto-char (car positions)) (move-to-column 5)
       (let ((before (buffer-substring-no-properties (line-beginning-position) (line-end-position))))
         (zk-home-refresh)
         (should (= 5 (current-column)))
         (should (equal before (buffer-substring-no-properties (line-beginning-position) (line-end-position)))))))))

(ert-deftest zk-home-cursor-redraw-preserves-window-start ()
  (zk-test-library
   (zk-test-cursor-fixture)
   (let* ((window (selected-window))
          (start (save-excursion (goto-char (point-min)) (forward-line 4) (point)))
          (text (save-excursion (goto-char start) (thing-at-point 'line t))))
     (set-window-start window start t)
     (zk-home--update '(agenda todos))
     (should (equal text (save-excursion (goto-char (window-start window)) (thing-at-point 'line t))))
     (should (string-match-p "Selected" (thing-at-point 'line t))))))

(ert-deftest zk-home-cursor-vanished-today-entry-does-not-jump-to-other-section ()
  (zk-test-library
   (let ((org-todo-keywords (list zk-org-todo-keywords))
         (org-use-fast-todo-selection t)
         (org-agenda-skip-scheduled-if-done t))
     (zk-test-cursor-fixture)
     (cl-letf (((symbol-function 'org-fast-todo-selection) (lambda (&rest _) "DONE")))
       (zk-home-agenda-todo))
     (should (equal "Agenda" (get-text-property (point) 'zk-section)))
     (zk-home--update '(agenda todos))
     (should (equal "Agenda" (get-text-property (point) 'zk-section))))))
