;;; zk-inbox-browse-tests.el --- Explicit edit mode and direct shortcuts -*- lexical-binding: t; -*-
(require 'zk-test-helper)

(ert-deftest zk-inbox-browse-edit-finish-retains-draft-until-explicit-save ()
  (zk-test-library
   (zk-process-inbox)
   (should buffer-read-only)
   (call-interactively (key-binding "e"))
   (should-not buffer-read-only)
   (dolist (key '("a" "p" "i" "c" "e" "t" "d" "w" "s" "l" "q"))
     (should (memq (key-binding key) '(self-insert-command org-self-insert-command))))
   (insert "apicetdwslq")
   (should-not (eq (key-binding (kbd "RET")) #'zk-inbox-review-apply))
   (call-interactively (key-binding (kbd "RET")))
   (insert "Second line")
   (let ((text (buffer-string)) (position (point)) (undo buffer-undo-list))
     (call-interactively (key-binding (kbd "C-c C-c")))
     (should buffer-read-only)
     (should-not zk-inbox-review--editing)
     (should (= (point) position))
     (should (eq buffer-undo-list undo))
     (should (equal text (buffer-string)))
     (should-not (file-exists-p (zk-inbox-path)))
     (call-interactively (key-binding "e"))
     (should (eq buffer-undo-list undo))
     (call-interactively (key-binding (kbd "<escape>")))
     (should buffer-read-only)
     (should (equal text (buffer-string))))
   (call-interactively (key-binding (kbd "RET")))
   (should (= 1 (length (zk-inbox-entries))))
   (should buffer-read-only)
   (should (string-empty-p (buffer-string)))))

(ert-deftest zk-inbox-browse-direct-actions-match-hints-in-editor-and-panels ()
  (zk-test-library
   (zk-capture "Old item")
   (zk-process-inbox) (zk-inbox-review-next)
   (call-interactively (key-binding "p"))
   (let ((labels (with-current-buffer zk-inbox-review--controls-name (buffer-string))))
     (dolist (pair '(("Inbox [i]" "i" zk-inbox-review-keep)
                     ("[Agenda] [p]" "p" zk-inbox-review-plan)
                     ("Archive [a]" "a" zk-inbox-review-archive)
                     ("Type [t]" "t" zk-inbox-review-type)
                     ("Location [d]" "d" zk-inbox-review-destination)
                     ("State [w]" "w" zk-inbox-review-state)
                     ("Scheduled [s]" "s" zk-inbox-review-schedule)
                     ("Deadline [l]" "l" zk-inbox-review-deadline)))
       (should (string-match-p (regexp-quote (car pair)) labels))
       (dolist (buffer (list zk-inbox-review-buffer-name zk-inbox-review--queue-name
                            zk-inbox-review--controls-name))
         (with-current-buffer buffer
           (should (eq (key-binding (cadr pair)) (nth 2 pair)))))))
   (should-not (string-match-p "C-c" (with-current-buffer zk-inbox-review--controls-name (buffer-string))))
   (should buffer-read-only)
   (call-interactively (key-binding "a"))
   (should-not (zk-inbox-entries))
   (should (eq 'new zk-inbox-review--selected))))

(ert-deftest zk-inbox-browse-panel-edit-returns-focus-to-body ()
  (zk-test-library
   (zk-process-inbox)
   (let ((editor (current-buffer)))
     (with-current-buffer zk-inbox-review--controls-name
       (call-interactively (key-binding "e")))
     (should (eq editor (window-buffer (selected-window))))
     (should-not buffer-read-only)
     (insert "Draft")
     (with-current-buffer zk-inbox-review--controls-name
       (should (eq (key-binding (kbd "RET")) #'push-button))
       (call-interactively (key-binding "i")))
     (should-not buffer-read-only)
     (should (equal "Draft" (buffer-string))))))

(ert-deftest zk-inbox-browse-switch-and-reopen-return-to-read-only ()
  (zk-test-library
   (zk-capture "Existing")
   (zk-process-inbox) (zk-inbox-review-edit) (insert "New draft")
   (zk-inbox-review-next)
   (should buffer-read-only)
   (zk-inbox-review-edit) (goto-char (point-max)) (insert "Added")
   (zk-inbox-review-new)
   (should buffer-read-only)
   (should (equal "New draft" (buffer-string)))
   (zk-inbox-review-edit)
   (zk-inbox-review-quit)
   (zk-process-inbox)
   (should buffer-read-only)
   (should (equal "New draft" (buffer-string)))
   (zk-inbox-review-next)
   (should (string-match-p "Added" (buffer-string)))))

(ert-deftest zk-inbox-browse-save-failure-retains-editing-state-and-content ()
  (zk-test-library
   (zk-process-inbox) (zk-inbox-review-edit) (insert "Draft")
   (zk-inbox-review-plan)
   (should-not (zk-inbox-review-apply))
   (should-not buffer-read-only)
   (should zk-inbox-review--editing)
   (should (equal "Draft" (buffer-string)))
   (zk-inbox-review-finish-edit)
   (should-not (zk-inbox-review-apply))
   (should buffer-read-only)
   (should (equal "Draft" (buffer-string)))))
