;;; zk-inbox-review-tests.el --- Unified collection and processing -*- lexical-binding: t; -*-
(require 'zk-test-helper)

(defun zk-test-inbox-text (text)
  (zk-inbox-review-edit) (erase-buffer) (insert text) (zk-inbox-review-finish-edit))
(defun zk-test-inbox-controls ()
  (with-current-buffer zk-inbox-review--controls-name (buffer-string)))

(ert-deftest zk-inbox-workspace-starts-in-new-with-a-read-only-empty-inbox ()
  (zk-test-library
   (cl-letf (((symbol-function 'read-string) (lambda (&rest _) (error "Unexpected prompt"))))
     (zk-process-inbox))
   (should (eq major-mode 'zk-inbox-review-mode))
   (should (derived-mode-p 'org-mode))
   (should buffer-read-only)
   (should (string-empty-p (buffer-string)))
   (should (eq zk-inbox-review--selected 'new))
   (should (string-match-p "Save to Inbox" (zk-test-inbox-controls)))
   (should-not (file-exists-p (zk-inbox-path)))
   (should (eq (key-binding "e") #'zk-inbox-review-edit))
   (should (eq (key-binding "a") #'zk-inbox-review-archive))
   (should (eq (key-binding (kbd "RET")) #'zk-inbox-review-apply))
   (should-error (insert "Accidental edit") :type 'buffer-read-only)))


(ert-deftest zk-inbox-workspace-capture-clears-composer-and-preserves-body ()
  (zk-test-library
   (zk-process-inbox)
   (zk-test-inbox-text "A thought\nA source https://example.com\n* Subtopic\nDetails\n")
   (let ((result (zk-inbox-review-apply)))
     (should result)
     (should-not (plist-get result :state))
     (should (string-match-p "\\*\\*\\* Subtopic" (plist-get (zk-entry-read result) :body))))
   (should (= 1 (length (zk-inbox-entries))))
   (should (string-empty-p (buffer-string)))
   (should (eq zk-inbox-review--selected 'new))
   (should-not (zk-inbox-review-apply))
   (should (= 1 (length (zk-inbox-entries))))))

(ert-deftest zk-inbox-workspace-direct-agenda-never-creates-inbox-file ()
  (zk-test-library
   (zk-process-inbox) (zk-test-inbox-text "Prepare report\nSome context")
   (zk-inbox-review-plan)
   (zk-inbox-review--set :destination '(:new-area "Work" :new-project "Quarterly report"))
   (zk-inbox-review--set :state "NEXT")
   (zk-inbox-review--set :scheduled "2026-10-01 10:00-11:00")
   (should (string-match-p "Save to Agenda" (zk-test-inbox-controls)))
   (should-not (file-exists-p (zk-agenda-path)))
   (should (zk-inbox-review-apply))
   (should-not (file-exists-p (zk-inbox-path)))
   (should (= 1 (length (zk-tasks "NEXT"))))
   (should (string-empty-p (buffer-string)))
   (should (eq (plist-get (zk-inbox-review--draft) :target) 'inbox))
   (should-not (plist-get (zk-inbox-review--draft) :destination))))

(ert-deftest zk-inbox-workspace-schedule-does-not-promote-todo ()
  (zk-test-library
   (zk-process-inbox) (zk-inbox-review-edit) (insert "Task") (zk-inbox-review-plan)
   (zk-inbox-review--set :destination '(:new-area "Life"))
   (zk-inbox-review--set :scheduled "2026-10-01")
   (should (zk-inbox-review-apply))
   (should (= 1 (length (zk-tasks "TODO"))))
   (should-not (zk-tasks "NEXT"))))

(ert-deftest zk-inbox-workspace-drafts-survive-navigation-and-return ()
  (zk-test-library
   (zk-capture "One") (zk-capture "Two")
   (let ((origin (current-buffer)))
     (zk-process-inbox) (zk-inbox-review-edit) (insert "New thought")
     (zk-inbox-review-next) (zk-test-inbox-text "Changed one\nMore")
     (zk-inbox-review-plan) (zk-inbox-review--set :state "NEXT")
     (zk-inbox-review-next)
     (should (string-prefix-p "Two" (buffer-string)))
     (zk-inbox-review-previous)
     (should (equal "Changed one\nMore" (buffer-string)))
     (should (equal "NEXT" (plist-get (zk-inbox-review--draft) :state)))
     (zk-inbox-review-new) (should (equal "New thought" (buffer-string)))
     (zk-inbox-review-quit) (should (eq (current-buffer) origin))
     (zk-process-inbox) (should (equal "New thought" (buffer-string)))
     (should (= 2 (length (zk-inbox-entries)))))))

(ert-deftest zk-inbox-workspace-edit-existing-keeps-id-tags-and-children ()
  (zk-test-library
   (let
       ((entry
         (zk-capture "Original" "Body\n*** Child\n:PROPERTIES:\n:ID: child-id\n:END:\nChild body\n")))
     (with-current-buffer (zk-org-buffer (zk-inbox-path))
       (goto-char (zk-org-locate entry)) (org-set-tags '("source")) (setq entry (zk-org-entry)))
     (zk-inbox-review-open entry)
     (should-not (string-match-p "ZK_TYPE" (buffer-string)))
     (should (string-match-p "^\\* Child" (buffer-string)))
     (zk-inbox-review-edit) (goto-char (point-min)) (delete-region (point) (line-end-position)) (insert "Edited")
     (should (string-match-p "Save changes" (zk-test-inbox-controls)))
     (let ((saved (zk-inbox-review-apply)))
       (should (equal (plist-get saved :id) (plist-get entry :id)))
       (should (member "source" (plist-get saved :tags)))
       (should (string-match-p "child-id" (plist-get (zk-entry-read saved) :body))))
     (should (= 1 (length (zk-inbox-entries))))
     (should (string-prefix-p "Edited" (buffer-string)))
     (should-not (plist-get (zk-inbox-review--draft) :dirty)))))

(ert-deftest zk-inbox-workspace-process-advances-without-inheriting-destination ()
  (zk-test-library
   (let ((project (zk-test-project)))
     (zk-capture "One") (zk-capture "Two")
     (zk-process-inbox) (zk-inbox-review-next) (zk-inbox-review-plan)
     (zk-inbox-review--set :destination project)
     (should (string-match-p "Move to Agenda" (zk-test-inbox-controls)))
     (should (zk-inbox-review-apply))
     (should (string-prefix-p "Two" (buffer-string)))
     (should-not (plist-get (zk-inbox-review--draft) :destination))
     (zk-inbox-review-plan)
     (should (string-match-p "Suggested" (zk-test-inbox-controls)))
     (should-not (zk-inbox-review-apply))
     (should (eq zk-inbox-review--error-field :destination)))))

(ert-deftest zk-inbox-workspace-errors-keep-text-and-do-not-create-files ()
  (zk-test-library
   (zk-process-inbox) (zk-inbox-review-edit) (insert "Appointment") (zk-inbox-review-plan)
   (should-not (zk-inbox-review-apply))
   (should (eq zk-inbox-review--error-field :destination))
   (zk-inbox-review--set :destination '(:new-area "Life"))
   (zk-inbox-review--set :kind 'event)
   (should-not (zk-inbox-review-apply))
   (should (eq zk-inbox-review--error-field :scheduled))
   (should (equal "Appointment" (buffer-string)))
   (should-not (file-exists-p (zk-agenda-path)))
   (should-not (file-exists-p (zk-inbox-path)))))

(ert-deftest zk-inbox-workspace-stale-source-requires-reload ()
  (zk-test-library
   (let ((entry (zk-capture "Original" "Body")))
     (zk-inbox-review-open entry) (zk-inbox-review-edit) (goto-char (point-max)) (insert "Local edits")
     (with-current-buffer (zk-org-buffer (zk-inbox-path))
       (goto-char (zk-org-locate entry)) (org-edit-headline "External edit"))
     (should-not (zk-inbox-review-apply))
     (should (string-match-p "changed" zk-inbox-review--error))
     (should (string-match-p "Local edits" (buffer-string)))
     (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil))) (zk-inbox-review-reload))
     (should (string-match-p "Local edits" (buffer-string)))
     (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))) (zk-inbox-review-reload))
     (should (string-prefix-p "External edit" (buffer-string)))
     (should-not (string-match-p "Local edits" (buffer-string))))))

(ert-deftest zk-inbox-workspace-unsaved-result-advances-without-repeating ()
  (zk-test-library
   (let ((project (zk-test-project)))
     (zk-capture "One") (zk-capture "Two")
     (with-current-buffer (zk-org-buffer (zk-agenda-path))
       (goto-char (point-max)) (insert "Draft\n"))
     (zk-process-inbox) (zk-inbox-review-next) (zk-inbox-review-plan)
     (zk-inbox-review--set :destination project)
     (let ((result (zk-inbox-review-apply))) (should result) (should-not (plist-get result :saved)))
     (should (string-match-p "in memory" zk-inbox-review--notice))
     (should (string-prefix-p "Two" (buffer-string)))
     (should (= 1 (length (zk-tasks)))))))

(ert-deftest zk-inbox-workspace-transaction-rolls-back-content-and-destination ()
  (zk-test-library
   (let* ((entry (zk-capture "Original" "Body"))
          (before (plist-get (zk-entry-read entry) :body)))
     (zk-inbox-review-open entry) (zk-test-inbox-text "Changed\nEdited body") (zk-inbox-review-plan)
     (zk-inbox-review--set :destination '(:new-area "Work" :new-project "New"))
     (cl-letf (((symbol-function 'zk-org-set-dates) (lambda (&rest _) (error "Injected failure"))))
       (should-not (zk-inbox-review-apply)))
     (should (equal before (plist-get (zk-entry-read entry) :body)))
     (should (equal "Changed\nEdited body" (buffer-string)))
     (should-not (zk-projects)))))

(ert-deftest zk-inbox-workspace-archive ()
  (zk-test-library
   (zk-capture "Obsolete")
   (zk-process-inbox) (zk-inbox-review-next)
   (should (zk-inbox-review-archive))
   (should-not (zk-inbox-entries))
   (should (eq zk-inbox-review--selected 'new))
   (should (string-empty-p (buffer-string)))))

(ert-deftest zk-inbox-workspace-archive-shortcut-commits-edits-and-advances ()
  (zk-test-library
   (let ((first (zk-capture "First" "Original body")))
     (zk-capture "Second")
     (zk-process-inbox) (zk-inbox-review-next)
     (zk-test-inbox-text "Edited first\nEdited body")
     ;; Archive must not require an Agenda destination even from that tab.
     (zk-inbox-review-plan)
     (call-interactively (key-binding (kbd "a")))
     (should (= 1 (length (zk-inbox-entries))))
     (should (string-prefix-p "Second" (buffer-string)))
     (should (string-prefix-p "Archived:" zk-inbox-review--notice))
     (with-current-buffer (zk-org-buffer (zk-agenda-path))
       (goto-char (zk-org-locate (plist-get first :id)))
       (should (org-in-archived-heading-p))
       (should (equal "Edited first" (zk-org-title)))
       (should (search-forward "Edited body" nil t))))))

(ert-deftest zk-inbox-workspace-archive-failure-keeps-current-draft ()
  (zk-test-library
   (let ((source (zk-capture "Original")))
     (zk-inbox-review-open source) (zk-test-inbox-text "Pending edit")
     (zk-inbox-review-plan)
     (with-current-buffer (zk-org-buffer (zk-inbox-path))
       (goto-char (zk-org-locate source)) (org-edit-headline "External edit"))
     (should-not (zk-inbox-review-archive))
     (should (equal "Pending edit" (buffer-string)))
     (should (eq 'agenda (plist-get (zk-inbox-review--draft) :target)))
     (should (= 1 (length (zk-inbox-entries))))
     (should-not (file-exists-p (zk-agenda-path))))))

(ert-deftest zk-inbox-workspace-new-draft-cannot-be-archived ()
  (zk-test-library
   (zk-process-inbox) (zk-inbox-review-edit) (insert "New draft")
   (should-error (zk-inbox-review-archive) :type 'user-error)
   (should (equal "New draft" (buffer-string)))
   (should-not (file-exists-p (zk-agenda-path)))
   (should-not (file-exists-p (zk-inbox-path)))))

(ert-deftest zk-inbox-workspace-date-input-keeps-ranges-and-cancellation ()
  (zk-test-library
   (zk-process-inbox) (zk-inbox-review-edit) (insert "Task") (zk-inbox-review-plan)
   (cl-letf (((symbol-function 'org-read-date)
              (lambda (&rest _) (setq org-end-time-was-given "17:00"
                                      org-read-date-final-answer "2026-10-01 16:00-17:00 +1w")
                "2026-10-01 16:00")))
     (zk-inbox-review-schedule))
   (should (equal "2026-10-01 16:00-17:00 +1w" (plist-get (zk-inbox-review--draft) :scheduled)))
   (cl-letf (((symbol-function 'org-read-date) (lambda (&rest _) (signal 'quit nil))))
     (condition-case nil (zk-inbox-review-deadline) (quit nil)))
   (should-not (plist-get (zk-inbox-review--draft) :deadline))
   (should (equal "Task" (buffer-string)))))

(ert-deftest zk-inbox-workspace-settings-do-not-move-editor-point-or-clear-undo ()
  (zk-test-library
   (zk-process-inbox) (zk-inbox-review-edit) (insert "Summary\nParagraph") (backward-char 4)
   (let ((position (point)) (text (buffer-string)) (undo buffer-undo-list))
     (zk-inbox-review-plan)
     (should (= position (point))) (should (equal text (buffer-string)))
     (should (eq undo buffer-undo-list)))))

(ert-deftest zk-inbox-workspace-source-child-selects-its-inbox-entry ()
  (zk-test-library
   (let ((entry (zk-capture "Parent" "*** Child\nChild body\n")))
     (zk-ui-open entry) (search-forward "Child body") (zk-process-inbox)
     (should (equal "Parent" (plist-get (zk-inbox-review--entry) :title))))))

(ert-deftest zk-inbox-workspace-drafts-prompt-on-kill-but-not-quit ()
  (zk-test-library
   (zk-process-inbox) (zk-inbox-review-edit) (insert "Keep draft")
   (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
     (should-not (kill-buffer (current-buffer))))
   (should (get-buffer zk-inbox-review-buffer-name))
   (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) (error "Unexpected prompt"))))
     (zk-inbox-review-quit))
   (zk-process-inbox) (should (equal "Keep draft" (buffer-string)))))

(ert-deftest zk-inbox-workspace-layout-wide-narrow-and-restored ()
  (zk-test-library
   (let ((width (frame-width)) (height (frame-height)))
     (unwind-protect
         (progn
           (set-frame-size nil 140 45)
           (delete-other-windows)
           (switch-to-buffer (current-buffer))
           (let ((origin (window-state-get nil t)))
             (zk-process-inbox)
             (should (get-buffer-window zk-inbox-review--queue-name))
             (should (get-buffer-window zk-inbox-review--controls-name))
             (set-frame-width nil 80)
             (zk-inbox-review--layout)
             (should-not (get-buffer-window zk-inbox-review--queue-name))
             (should (get-buffer-window zk-inbox-review-buffer-name))
             (zk-inbox-review-quit)
             (should (= 1 (length (window-list))))
             (should
              (equal (alist-get 'buffer (cdr origin))
                     (alist-get 'buffer (cdr (window-state-get nil t)))))))
       (set-frame-size nil width height)))))

(provide 'zk-inbox-review-tests)
