;;; zk-layout-tests.el --- Dashboard display layout tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'zk-home)

(ert-deftest zk-layout-mixed-script-columns-share-anchors ()
  (dolist (width '(45 80 130))
    (dolist (kind '(task inbox note))
      (with-temp-buffer
        (let* ((columns (zk-home--table-columns kind width))
               (entries (mapcar
                         (lambda (title)
                           (list :title title :file (concat "/tmp/" title ".org")
                                 :path (list "生活" "读书计划" title)
                                 :origin "资料收集" :tags '("知识" "Emacs")))
                         '("An English title" "中文与 English 混排"
                           "非常长的中文笔记标题用于确认后续列不会被挤偏移"))))
          (cl-letf (((symbol-function 'zk-home--columns) (lambda () width)))
            (zk-home--section "Example" entries kind))
          (goto-char (point-min))
          (search-forward (pcase kind ('task "TASK") ('inbox "ITEM") (_ "FILE")))
          (let (header-anchors)
            (while (< (point) (line-end-position))
              (when-let* ((display (get-text-property (point) 'display)))
                (cl-pushnew display header-anchors :test #'equal))
              (forward-char))
            (should (= (length header-anchors) (1- (length columns))))
            (forward-line 2)
            (dolist (entry entries)
              (let (anchors)
                (should (eq (get-text-property (point) 'zk-entry) entry))
                (should (button-at (point)))
                (while (< (point) (line-end-position))
                  (when-let* ((display (get-text-property (point) 'display)))
                    (cl-pushnew display anchors :test #'equal))
                  (forward-char))
                (should (equal anchors header-anchors)))
              (forward-line 1))))))))

(ert-deftest zk-layout-truncates-by-glyph-width ()
  ;; Model a fallback font with CJK glyphs wider than two Latin cells.
  (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
            ((symbol-function 'window-font-width) (lambda (&rest _) 10))
            ((symbol-function 'string-pixel-width)
             (lambda (s &rest _)
               (cl-loop for ch across s sum (if (> ch 127) 27 10)))))
    (should (equal (zk-home--fit "中文中文中文" 8) "中…"))
    (should (equal (zk-home--fit "Read 中文" 12) "Read 中文"))
    (should (equal (zk-home--fit "A\nB\tC" 8) "A B C"))
    (should (equal (zk-home--fit "" 8) ""))))

(ert-deftest zk-layout-terminal-uses-display-cells ()
  (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) nil)))
    (should (equal (zk-home--fit "中文中文中文" 8) "中文中…"))
    (should (<= (string-width (zk-home--fit "中文English很长" 8)) 8))))

(provide 'zk-layout-tests)
