;;; zk-refresh-tests.el --- Cache invalidation and refresh scope -*- lexical-binding: t; -*-
(require 'zk-test-helper)

(ert-deftest zk-notes-cache-observes-live-edits-save-and-buffer-close ()
  (zk-test-library
   (let* ((note (zk-note-create "Original.org"))
          (file (plist-get note :file))
          (reader (symbol-function 'zk-notes--read-metadata)) (reads 0))
     (zk-notes-clear-cache)
     (cl-letf (((symbol-function 'zk-notes--read-metadata)
                (lambda (&rest args) (cl-incf reads) (apply reader args))))
       (zk-notes) (zk-notes)
       (should (= reads 1))
       (with-current-buffer (get-file-buffer file)
         (goto-char (point-min))
         (search-forward ":END:") (forward-line 1) (insert "#+title: Edited\n"))
       (should (equal "Edited" (plist-get (car (zk-notes)) :title)))
       (should (plist-get (car (zk-notes)) :modified))
       (should (= reads 2))
       (with-current-buffer (get-file-buffer file) (save-buffer))
       (should-not (plist-get (car (zk-notes)) :modified))
       (should (= reads 3))
       (kill-buffer (get-file-buffer file))
       (should (equal "Edited" (plist-get (car (zk-notes)) :title)))
       (should (= reads 4))))))

(ert-deftest zk-notes-cache-observes-external-edit-addition-and-deletion ()
  (zk-test-library
   (let ((file (zk-test-write (zk-path "notes/old.org") "#+title: Old\n")))
     (should (equal "Old" (plist-get (car (zk-notes)) :title)))
     (zk-test-write file "#+title: Changed externally\n")
     (should (equal "Changed externally" (plist-get (car (zk-notes)) :title)))
     (zk-test-write (zk-path "notes/new.org") "#+title: Added\n")
     (should (= 2 (length (zk-notes))))
     (delete-file file)
     (should (= 1 (length (zk-notes))))
     (should-not (gethash file zk-notes--cache)))))

(ert-deftest zk-notes-cache-cannot-be-modified-by-a-consumer ()
  (zk-test-library
   (let* ((note (zk-note-create "Original.org")) (file (plist-get note :file))
          (record (zk-note-metadata file)))
     (plist-put record :title "Corrupted")
     (should (equal "Original" (plist-get (zk-note-metadata file) :title))))))

(ert-deftest zk-home-time-and-layout-refresh-do-not-rescan-notes ()
  (zk-test-library
   (zk-capture "Item") (zk-note-create "Note.org")
   (zk-home)
   (let ((notes (symbol-function 'zk-notes)) (tasks (symbol-function 'zk-tasks-overview))
         (inbox (symbol-function 'zk-inbox-entries)) calls)
     (cl-letf (((symbol-function 'zk-notes) (lambda () (push 'notes calls) (funcall notes)))
               ((symbol-function 'zk-tasks-overview)
                (lambda (&rest args) (push 'tasks calls) (apply tasks args)))
               ((symbol-function 'zk-inbox-entries) (lambda () (push 'inbox calls) (funcall inbox))))
       (zk-home--update '(agenda))
       (zk-home--update '(layout))
       (should-not calls)
       (zk-home--update '(inbox))
       (should (equal '(inbox) calls))
       (setq calls nil)
       (zk-home-refresh)
       (should (equal '(inbox notes tasks) (sort calls #'string<)))))))

(ert-deftest zk-home-file-changes-queue-only-affected-sections ()
  (zk-test-library
   (zk-home)
   (let (queued)
     (cl-letf (((symbol-function 'zk-home--queue) (lambda (sections) (setq queued sections))))
       (zk-home-request-refresh (list (zk-inbox-path)))
       (should (equal '(inbox) queued))
       (zk-home-request-refresh (list (zk-agenda-path)))
       (should (equal '(agenda todos) (sort queued #'string<)))
       (zk-home-request-refresh (list (zk-path "notes/idea.org")))
       (should (equal '(notes) queued))))))

(ert-deftest zk-home-killing-buffer-stops-both-refresh-timers ()
  (zk-test-library
   (zk-home)
   (zk-home--queue '(agenda))
   (let ((clock zk-home--clock-timer) (idle zk-home--timer))
     (kill-buffer (current-buffer))
     (should-not (memq clock timer-list))
     (should-not (memq idle timer-idle-list)))))
