;;; zk-todos-tests.el --- Daily Todos and project selection -*- lexical-binding: t; -*-
(require 'zk-test-helper)

(defmacro zk-test-todos (&rest body)
  (declare (indent 0))
  `(zk-test-library
    (let ((org-todo-keywords (list zk-org-todo-keywords))
          (org-use-fast-todo-selection t) (org-log-done 'time) (org-log-repeat 'time))
      ,@body)))

(defun zk-test-todos-date (&optional day-offset time)
  (let ((date (calendar-gregorian-from-absolute (+ (org-today) (or day-offset 0)))))
    (format "[%04d-%02d-%02d%s]" (nth 2 date) (car date) (cadr date) (or time " 10:00"))))

(defun zk-test-todos-point (title)
  (goto-char (zk-home--section-start "Todos"))
  (while (and (equal "Todos" (get-text-property (point) 'zk-section))
              (not (equal title (plist-get (get-text-property (point) 'zk-entry) :title))))
    (forward-line 1))
  (should (equal title (plist-get (get-text-property (point) 'zk-entry) :title))))

(defun zk-test-todos-state (state)
  (cl-letf (((symbol-function 'org-fast-todo-selection) (lambda (&rest _) state)))
    (call-interactively (key-binding "t"))))

(defun zk-test-todos-daily ()
  (plist-get (plist-get zk-home--data :todos) :daily))

(ert-deftest zk-todos-daily-uses-completion-date-and-lists-every-next ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path)
                   (concat "* Work\n"
                           (mapconcat (lambda (i) (format "** NEXT Task %d\n" i)) (number-sequence 1 7) "")
                           (format "** DONE Early\nCLOSED: %s SCHEDULED: <2099-01-01>\n" (zk-test-todos-date 0 " 08:00"))
                           (format "** DONE Recent\nCLOSED: %s SCHEDULED: <2000-01-01>\n" (zk-test-todos-date 0 " 14:00"))
                           (format "** DONE Yesterday\nCLOSED: %s\n" (zk-test-todos-date -1))
                           (format "** DONE Future\nCLOSED: %s\n" (zk-test-todos-date 1))
                           "** DONE Undated\n** TODO Backlog\n"
                           "* Archived :ARCHIVE:\n** NEXT Archived task\n"
                           "* COMMENT Ignored\n** NEXT Commented task\n"))
    (let ((daily (plist-get (zk-tasks-overview) :daily)))
      (should (equal (mapcar (lambda (e) (plist-get e :title)) daily)
                     '("Task 1" "Task 2" "Task 3" "Task 4" "Task 5" "Task 6" "Task 7" "Recent" "Early"))))
    (zk-home)
    (zk-test-todos-point "Recent")
    (should (string-prefix-p "DONE " (thing-at-point 'line t)))
    (zk-test-todos-point "Task 7")
    (should (string-prefix-p "NEXT " (thing-at-point 'line t)))
    (let ((before (buffer-string)) (position (point)))
      (call-interactively (key-binding (kbd "TAB")))
      (should (equal before (buffer-string)))
      (should (= position (point))))))

(ert-deftest zk-todos-status-colors-and-return-only-open-source ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path)
                   (format "* Work\n** NEXT Ready\n** DONE Finished\nCLOSED: %s\n" (zk-test-todos-date)))
    (zk-home)
    (dolist (pair '(("Ready" . zk-org-next) ("Finished" . zk-org-finished)))
      (zk-test-todos-point (car pair))
      (should (eq (cdr pair) (get-text-property (point) 'face)))
      (should (eq (if (equal (car pair) "Finished") 'zk-org-finished 'zk-home-entry)
                  (get-text-property (+ 5 (point)) 'face)))
      (let ((entry (get-text-property (point) 'zk-entry)) opened)
        (cl-letf (((symbol-function 'zk-ui-open) (lambda (ref) (setq opened ref))))
          ;; Prefix, title and trailing metadata must all navigate.
          (dolist (column '(0 7 65))
            (move-to-column column)
            (call-interactively (key-binding (kbd "RET")))
            (should (eq opened entry))))
        (should (equal (plist-get entry :state) (plist-get (zk-entry-read entry) :state)))))))

(ert-deftest zk-todos-done-can-be-reopened-with-native-keys-and-stable-selection ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path) "* Work\n** NEXT Earlier\n** NEXT Selected\n")
    (zk-home)
    (zk-test-todos-point "Selected") (move-to-column 8)
    (let ((home (current-buffer)) (window (selected-window))
          (zk-change-hook '(zk-home-request-refresh)))
      (zk-test-todos-state "DONE")
      (should (eq home (current-buffer))) (should (eq home (window-buffer window)))
      (should (= 8 (current-column)))
      (should (equal "Todos" (get-text-property (point) 'zk-section)))
      (should (string-prefix-p "DONE Selected" (thing-at-point 'line t)))
      (should (plist-get (get-text-property (point) 'zk-entry) :closed))
      (let ((timer zk-home--timer))
        (cancel-timer timer) (funcall (timer--function timer)))
      (should (string-prefix-p "DONE Selected" (thing-at-point 'line t)))
      (zk-test-todos-state "NEXT")
      (should (string-prefix-p "NEXT Selected" (thing-at-point 'line t)))
      (should (= 1 (seq-count (lambda (e) (equal "Selected" (plist-get e :title))) (zk-test-todos-daily))))
      (should-not (plist-get (get-text-property (point) 'zk-entry) :closed))
      (with-current-buffer (get-file-buffer (zk-agenda-path)) (should-not (buffer-modified-p))))))

(ert-deftest zk-todos-native-change-keeps-earlier-unsaved-edits ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path) "* Work\n** NEXT Selected\n")
    (zk-home) (zk-test-todos-point "Selected")
    (with-current-buffer (get-file-buffer (zk-agenda-path))
      (goto-char (point-min)) (insert "#+title: Unsaved\n"))
    (zk-test-todos-state "DONE")
    (should (string-prefix-p "DONE Selected" (thing-at-point 'line t)))
    (with-current-buffer (get-file-buffer (zk-agenda-path))
      (should (buffer-modified-p)) (should (string-match-p "Unsaved" (buffer-string))))
    (with-temp-buffer
      (insert-file-contents (zk-agenda-path))
      (should (equal "* Work\n** NEXT Selected\n" (buffer-string))))))

(ert-deftest zk-todos-repeat-completion-uses-native-log-without-duplicating-next ()
  (zk-test-todos
    (let ((day (substring (zk-test-todos-date) 1 11)))
      (zk-test-write (zk-agenda-path)
                     (format "* Life\n** NEXT Exercise\nSCHEDULED: <%s 09:00 +1d>\n" day)))
    (zk-home) (zk-test-todos-point "Exercise")
    (zk-test-todos-state "DONE")
    (let* ((entry (get-text-property (point) 'zk-entry)) (scheduled (plist-get entry :scheduled)))
      (should (equal "TODO" (plist-get entry :state)))
      (should (equal "DONE" (zk-task-display-state entry)))
      (should (= 1 (length (zk-test-todos-daily))))
      (should (> (org-time-string-to-absolute scheduled) (org-today)))
      (let ((tomorrow (1+ (org-today))))
        (cl-letf (((symbol-function 'org-today) (lambda () tomorrow)))
          (should-not (plist-get (zk-tasks-overview) :daily))))
      (zk-test-todos-state "NEXT")
      (should (= 1 (length (zk-test-todos-daily))))
      (should (equal "NEXT" (zk-task-display-state (car (zk-test-todos-daily)))))
      (should (equal scheduled (plist-get (car (zk-test-todos-daily)) :scheduled))))))

(ert-deftest zk-todos-last-repeat-without-done-log-is-not-completion ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path)
                   (format "* Life\n** TODO Unconfirmed\nSCHEDULED: <2099-01-01 +1d>\n:PROPERTIES:\n:LAST_REPEAT: %s\n:END:\n"
                           (zk-test-todos-date)))
    (should-not (plist-get (zk-tasks-overview) :daily))))

(ert-deftest zk-todos-project-tree-retains-real-outline-and-source-order ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path)
                   "* 工作\n** Z project\n*** TODO Later\n*** NEXT Ready\n** A project\n*** TODO Earlier\n* 生活\n** TODO Errand\n* Empty\n** DONE Old\n* Archive :ARCHIVE:\n** NEXT Hidden\n")
    (let* ((data (zk-tasks-overview)) (roots (plist-get data :projects))
           (work (car roots)) (projects (plist-get work :children)))
      (should (equal '("工作" "生活") (mapcar (lambda (n) (plist-get (plist-get n :entry) :title)) roots)))
      (should (equal '("Z project" "A project") (mapcar (lambda (n) (plist-get (plist-get n :entry) :title)) projects)))
      (should (= 2 (plist-get work :todo))) (should (= 1 (plist-get work :next)))
      (should (= 2 (length (plist-get (car (plist-get data :daily)) :ancestor-keys))))
      (should (= 1 (plist-get (cadr roots) :todo))))))

(ert-deftest zk-todos-project-selection-folds-in-place-and-remembers-location ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path) "* Work\n** Project\n*** TODO Backlog\n*** NEXT Ready\n")
    (zk-home) (goto-char (zk-home--section-start "Todos"))
    (call-interactively (key-binding "i"))
    (should (eq zk-home--todos-view 'projects))
    (should-not (string-match-p "Backlog" (buffer-string)))
    (zk-test-todos-point "Work") (call-interactively (key-binding (kbd "TAB")))
    (zk-test-todos-point "Project")
    (search-forward "Project") (backward-char)
    (should (button-at (point)))
    (call-interactively (key-binding (kbd "TAB")))
    (zk-test-todos-point "Backlog")
    (zk-test-todos-state "NEXT")
    (should (eq zk-home--todos-view 'projects))
    (should (equal "Backlog" (plist-get (get-text-property (point) 'zk-entry) :title)))
    (should (string-match-p "0 TODO · 2 NEXT" (buffer-string)))
    (call-interactively (key-binding (kbd "<escape>")))
    (should (eq zk-home--todos-view 'daily))
    (should (string-prefix-p "NEXT Backlog" (thing-at-point 'line t)))
    (call-interactively (key-binding "i"))
    (should (equal "Backlog" (plist-get (get-text-property (point) 'zk-entry) :title)))
    (should (= 2 (length zk-home--project-expanded)))
    ;; Inserting before an idless root must not close the selected branch.
    (with-current-buffer (get-file-buffer (zk-agenda-path))
      (goto-char (point-min)) (insert "#+title: Draft\n")
      (search-forward "Project") (org-edit-headline "Renamed project"))
    (zk-home-refresh)
    (should (equal "Backlog" (plist-get (get-text-property (point) 'zk-entry) :title)))
    (should (string-match-p "Renamed project" (buffer-string)))
    (call-interactively (key-binding (kbd "TAB")))
    (should (equal "Renamed project" (plist-get (get-text-property (point) 'zk-entry) :title)))
    (should-not (string-match-p "NEXT Backlog" (buffer-string)))))

(ert-deftest zk-todos-i-on-task-expands-its-ancestors ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path) "* Work\n** Project\n*** NEXT Selected\n")
    (zk-home) (zk-test-todos-point "Selected")
    (call-interactively (key-binding "i"))
    (should (eq zk-home--todos-view 'projects))
    (should (= 2 (length zk-home--project-expanded)))
    (should (equal "Selected" (plist-get (get-text-property (point) 'zk-entry) :title)))))

(ert-deftest zk-todos-insert-is-contextual-and-inbox-enters-editing ()
  (zk-test-todos
    (zk-home)
    (dolist (section '("Agenda" "Notes"))
      (goto-char (zk-home--section-start section))
      (should-error (call-interactively (key-binding "i")) :type 'user-error)
      (should (equal "*ZK*" (buffer-name))))
    (goto-char (zk-home--section-start "Inbox"))
    (call-interactively (key-binding "i"))
    (should (derived-mode-p 'zk-inbox-review-mode))
    (should (eq 'new zk-inbox-review--selected))
    (should-not buffer-read-only)
    (insert "Unsubmitted item")
    (should-not (zk-inbox-entries))))

(ert-deftest zk-todos-midnight-refresh-removes-yesterday-without-reading-notes ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path) (format "* Work\n** DONE Finished\nCLOSED: %s\n" (zk-test-todos-date)))
    (zk-home)
    (should (= 1 (length (zk-test-todos-daily))))
    (let ((tomorrow (1+ (org-today))))
      (cl-letf (((symbol-function 'org-today) (lambda () tomorrow))
                ((symbol-function 'zk-notes) (lambda () (error "Do not query notes"))))
        (funcall (timer--function zk-home--clock-timer))
        (should (memq 'todos zk-home--dirty))
        (let ((timer zk-home--timer))
          (cancel-timer timer) (funcall (timer--function timer)))
        (should-not (zk-test-todos-daily))
        (should (= tomorrow zk-home--todos-day))))))

(ert-deftest zk-todos-native-cancel-blocker-and-stale-entry-preserve-source ()
  (zk-test-todos
    (zk-test-write (zk-agenda-path) "* Work\n** NEXT Selected\n")
    (zk-home) (zk-test-todos-point "Selected")
    (cl-letf (((symbol-function 'org-fast-todo-selection) (lambda (&rest _) (signal 'quit nil))))
      (should (eq 'quit (condition-case nil (zk-home-todo) (quit 'quit)))))
    (should (equal "NEXT" (plist-get (car (zk-test-todos-daily)) :state)))
    (let ((org-blocker-hook (list (lambda (_) nil))))
      (zk-test-todos-state "DONE")
      (should (equal "NEXT" (plist-get (car (zk-test-todos-daily)) :state))))
    (with-current-buffer (get-file-buffer (zk-agenda-path))
      (goto-char (point-min)) (search-forward "Selected") (org-edit-headline "Edited elsewhere"))
    (should-error (zk-test-todos-state "DONE") :type 'user-error)
    (should (equal "*ZK*" (buffer-name)))))

;;; zk-todos-tests.el ends here
